"""Initial migration

Revision ID: 90e140cf2e2c
Revises: 
Create Date: 2024-12-02 21:07:10.875945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90e140cf2e2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rentals')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('student_id')
        batch_op.drop_index('username')

    op.drop_table('users')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index('isbn')

    op.drop_table('books')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('year')
        batch_op.drop_column('department')
        batch_op.drop_column('phone')
        batch_op.drop_column('student_id')

    op.create_table('books',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('author', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('genre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('publication_year', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('isbn', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('availability', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index('isbn', ['isbn'], unique=True)

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('department', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.create_index('student_id', ['student_id'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('rentals',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rental_date', sa.DATE(), nullable=False),
    sa.Column('return_date', sa.DATE(), nullable=False),
    sa.Column('actual_return_date', sa.DATE(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='rentals_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='rentals_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
